#!/bin/bash

#==============================================================================
# WinForms Coding Standards - Project Setup (Linux/Mac)
#==============================================================================
# This script integrates the WinForms Coding Standards repository into your
# project using Git Submodule. It creates symlinks for Claude Code commands.
#
# Usage:
#   ./setup-standards.sh [PROJECT_PATH] [STANDARDS_REPO]
#
# Examples:
#   ./setup-standards.sh
#   ./setup-standards.sh ~/Projects/MyApp
#   ./setup-standards.sh . https://github.com/yourorg/winforms-standards.git
#==============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Print functions
print_success() { echo -e "${GREEN}[OK] $1${NC}"; }
print_info() { echo -e "${CYAN}[INFO] $1${NC}"; }
print_warning() { echo -e "${YELLOW}[WARN] $1${NC}"; }
print_error() { echo -e "${RED}[ERROR] $1${NC}"; }

# Banner
echo ""
echo -e "${CYAN}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║                                                           ║${NC}"
echo -e "${CYAN}║     WinForms Coding Standards - Project Setup            ║${NC}"
echo -e "${CYAN}║                                                           ║${NC}"
echo -e "${CYAN}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

# Parse arguments
PROJECT_PATH="${1:-.}"
STANDARDS_REPO="${2:-}"

# Get absolute path
PROJECT_PATH=$(cd "$PROJECT_PATH" && pwd)
print_info "Target project: $PROJECT_PATH"
echo ""

# Check if Git is installed
if ! command -v git &> /dev/null; then
    print_error "Git is not installed!"
    echo "Please install Git: https://git-scm.com/downloads"
    exit 1
fi

# Navigate to project
cd "$PROJECT_PATH"

# Check if project is a Git repository
if [ ! -d ".git" ]; then
    print_warning "Project is not a Git repository."
    read -p "Initialize Git repository? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git init
        print_success "Git repository initialized"
    else
        print_error "Git repository required for submodule setup"
        exit 1
    fi
fi

# Auto-detect standards repo URL if not provided
if [ -z "$STANDARDS_REPO" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    cd "$SCRIPT_DIR/.."
    STANDARDS_REPO=$(git remote get-url origin 2>/dev/null || echo "")
    cd "$PROJECT_PATH"

    if [ -n "$STANDARDS_REPO" ]; then
        print_info "Detected standards repo: $STANDARDS_REPO"
    else
        print_warning "Could not detect standards repository URL"
        read -p "Enter standards repository URL (or path): " STANDARDS_REPO
    fi
fi

# Check if .standards submodule already exists
if [ -d ".standards" ]; then
    print_warning "'.standards' directory already exists"
    read -p "Remove and reinstall? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git submodule deinit -f .standards 2>/dev/null || true
        git rm -f .standards 2>/dev/null || true
        rm -rf .standards
        rm -rf .git/modules/.standards
        print_success "Removed existing .standards"
    else
        print_info "Keeping existing setup"
        exit 0
    fi
fi

# Add submodule
print_info "Adding standards as Git submodule..."
echo ""

git submodule add "$STANDARDS_REPO" .standards
git submodule update --init --recursive
print_success "Standards submodule added successfully!"

echo ""

# Create symlinks for easy access
print_info "Creating symlinks for convenience..."

# Symlink .claude commands
if [ ! -e ".claude" ]; then
    ln -s .standards/.claude .claude
    print_success "Created symlink: .claude -> .standards/.claude"
fi

# Symlink templates
if [ ! -e "templates" ]; then
    ln -s .standards/templates templates
    print_success "Created symlink: templates -> .standards/templates"
fi

echo ""

# Create .clauderc to load CLAUDE.md from submodule
print_info "Configuring Claude Code integration..."

cat > .clauderc << 'EOF'
# Claude Code Configuration
# Auto-generated by setup-standards.sh

# Load coding standards from submodule
# This allows Claude Code to access standards even though they're in .standards/
EOF

print_success "Created .clauderc configuration"

# Update .gitignore
if [ -f ".gitignore" ]; then
    if ! grep -q ".clauderc" .gitignore; then
        echo -e "\n# Claude Code config (optional)\n.clauderc" >> .gitignore
        print_success "Updated .gitignore"
    fi
else
    echo -e "# Claude Code config (optional)\n.clauderc" > .gitignore
    print_success "Created .gitignore"
fi

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                                                           ║${NC}"
echo -e "${GREEN}║                   Setup Complete!                      ║${NC}"
echo -e "${GREEN}║                                                           ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

# Summary
echo -e "${CYAN}[Standards Location]${NC}"
echo "   $PROJECT_PATH/.standards"
echo ""

echo -e "${CYAN}[Documentation]${NC}"
echo "   .standards/README.md          - Overview"
echo "   .standards/USAGE_GUIDE.md     - Practical examples"
echo "   .standards/CLAUDE.md          - AI assistant guide"
echo "   .standards/docs/              - Full documentation"
echo ""

echo -e "${CYAN}[Available Resources]${NC}"
if [ -L ".claude" ]; then
    echo "   [OK] .claude/commands/          - Slash commands (symlinked)"
else
    echo "   [DIR] .standards/.claude/commands/ - Slash commands"
fi

if [ -L "templates" ]; then
    echo "   [OK] templates/                 - Code templates (symlinked)"
else
    echo "   [DIR] .standards/templates/      - Code templates"
fi
echo ""

echo -e "${CYAN}[Quick Start]${NC}"
echo "   1. Read: .standards/USAGE_GUIDE.md"
echo "   2. Use Claude Code slash commands (type / to see list)"
echo "   3. Copy templates from .standards/templates/"
echo "   4. Follow conventions in .standards/docs/"
echo ""

echo -e "${CYAN}[Update Standards]${NC}"
echo "   cd .standards"
echo "   git pull origin main"
echo "   cd .."
echo ""

echo -e "${YELLOW}[Pro Tips]${NC}"
echo "   - Commit .gitmodules and .standards to your repo"
echo "   - Team members: run 'git submodule update --init' after clone"
echo "   - Standards update automatically when you pull latest"
echo ""

print_success "Ready to code!"
